CC=gcc
main: main.o display.o vend_func.o owner.o print_bill.o grand_total.o payment.o 
	gcc main.o display.o vend_func.o owner.o print_bill.o grand_total.o payment.o -o cproj
main.o: main.o
	gcc -c main.c
display.o: display.o
	gcc -c display.c
vend_func.o: vend_func.o
	gcc -c vend_func.c
owner.o: owner.o
	gcc -c owner.c
print_bill.o: print_bill.o
	gcc -c print_bill.c
grand_total.o: grand_total.o
	gcc -c grand_total.c
payment.o: payment.o
	gcc -c payment.c



















